version: '3.4'

networks:
  dev:
    driver: bridge

services:
  backend:
    image: docker.io/library/backend
    depends_on:
      - "backend_db"
    container_name: backend-services
    ports:
      - 8020:80
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=backend_db;Port=5432;Database=backenddb;User Id=postgres;Password=postgres;
    command: bash -c "dotnet ef database update && dotnet run --urls=http://+:80/"
    networks:
      - dev
  backend_db:
    image: postgres:latest
    container_name: backend_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=backenddb
    ports:
      - 5454:5432
    restart: always
    volumes:
      - C:/SavedDBData:/var/lib/postgresql/data
    networks:
      - dev